version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.2.5-apache-node
      - image: circleci/mariadb:10.3.4-ram
        environment:
          - MYSQL_DATABASE: wordpress
          - MYSQL_USER: admin
          - MYSQL_PASSWORD: password

    working_directory: ~/wp-php-console

    steps:
      - checkout
      # Set up hosts
      - run: echo 127.0.0.1 wp-php-console.test | sudo tee -a /etc/hosts
      # Ensure we have a MySQL client
      - run: sudo apt-get -y install mysql-client
      # Grab WP CLI and make it executable
      - run: curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
      - run: chmod +x wp-cli.phar
      # Download WordPress into `wordpress` directory
      - run: ./wp-cli.phar core download --allow-root --path=wordpress
      # Generate `wp-config.php` file
      - run: ./wp-cli.phar core config --allow-root --dbname=wordpress --dbuser=ubuntu --dbhost=localhost --path=wordpress
      # Install WordPress
      - run: ./wp-cli.phar core install --allow-root --admin_name=admin --admin_password=admin --admin_email=admin@example.com --url=http://wppusher-plugin.dev:8080 --title=WordPress --path=wordpress
      # Clone WP PHP Console plugin from GitHub...
      - run: git clone git@github.com:unfulvio/wp-php-console.git wordpress/wp-content/plugins/wp-php-console
      # ...and use WP-CLI to activate it
      - run: ./wp-cli.phar plugin activate wp-php-console --path=wordpress
      # Install plugin's Composer dependencies
      - run: cd wordpress/wp-content/plugins/wp-php-console
      - run: composer install
      # Restart Apache and run tests
      - run: sudo service apache2 restart
      - run: vendor/bin/codecept run
