version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.2.5-apache-node
      - image: circleci/mariadb:10.3.6-ram
        environment:
          - MYSQL_DATABASE: wordpress
          - MYSQL_USER: admin
          - MYSQL_PASSWORD: password

    working_directory: ~/wp-php-console

    steps:
      - checkout
      # Prepare hosts
      - run: echo 127.0.0.1 wp-php-console.test | sudo tee -a /etc/hosts
      # Install and configure some libraries required by Codeception or plugin
      - run: sudo apt-get install libzip-dev libfreetype6-dev libjpeg62-turbo-dev libmcrypt-dev libpng-dev mysql-client -y
      - run: sudo docker-php-ext-install -j$(nproc) mbstring zip gd
      - run: sudo docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
      # Install Chrome headless
      # - run: sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      # - run: sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
      # - run: sudo apt-get update
      # Install plugin dependencies via Composer
      - run: composer install
      - run: mkdir plugin
      # Make a copy of the plugin to move later to WordPress folder
      - run: cp -r -a . plugin || true
      # Install WP CLI
      - run: curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
      - run: chmod +x wp-cli.phar
      # Install and configure WordPress
      - run: ./wp-cli.phar core download --allow-root --path=wordpress || true
      - run: ./wp-cli.phar core config --allow-root --dbname=wordpress --dbuser=admin --dbpass=password --dbhost=127.0.0.1 --path=wordpress || true
      - run: ./wp-cli.phar c# ore install --allow-root --admin_name=admin --admin_password=password --admin_email=admin@example.com --url=http://wp-php-console.test:8080 --title="WP PHP Console Tests" --path=wordpress || true
      # Move plugin into WordPress and activate
      - run: mv plugin wordpress/wp-content/plugins/wp-php-console
      - run: ./wp-cli.phar plugin activate wp-php-console --path=wordpress || true
      # Restart Apache and run tests
      - run: sudo service apache2 restart
      - run: cd wordpress/wp-content/plugins/wp-php-console
      - run: vendor/bin/codecept run acceptance
